# Generated by Django 4.2.14 on 2024-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_remove_todo_list_status_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
