# Generated by Django 4.2.14 on 2024-08-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0005_rename_created_task_created_on_task_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_list_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
