# Generated by Django 4.2.14 on 2024-08-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on']},
        ),
    ]
